# Склады в Екатеринбурге, в выборку попадают указанные склады,
# анализируем любые даты с коэф. приемки 5 и типом поставки "Короба"
- warehouse:
    - "Екатеринбург - Испытателей 14г"
    - "Екатеринбург - Перспективный 12/2"
    - "СЦ Екатеринбург 2 (Альпинистов)"
  delay: 0
  max_coefficient: 5
  boxTypeName: "Короба"
  
# Удаленные склады, в выборку попадают любые склады, со свободными слотами
# не ранее, чем через 7 дней, с коэф. приемки 5 и типом поставки "Короба"
- delay: 7
  warehouse:
    - "Электросталь"
    - "Коледино"
    - "Тула"
  max_coefficient: 5
  boxTypeName: "Короба"
